### PR TITLE
Add LICENSE in MANIFEST.in

### PR DESCRIPTION
**Pull request by slel**
Needed for packaging in Conda.

### CODE REVIEW

**Comment by EugeneLoy** [comment]
@slel Thank you! Will merge now and release it as `1.5.1` a bit later today.

**Comment by EugeneLoy** [comment]
@slel Done.
BTW, are you building `coq_jupyter` package for Conda? Do you intend to publish it?

**Comment by slel** [comment]
@EugeneLoy -- yes, @isuruf and I are doing some Conda packaging at

> Sage Days 101
> https://wiki.sagemath.org/days101

and @Zimmi48 told me having coq-jupyter packaged for Conda
would be nice when we met at

> Free Computational Mathematics
> https://opendreamkit.org/2019/02/11/FreeComputationalMathematicsConference/

and this is now done at https://github.com/conda-forge/coq-jupyter-feedstock
-- let me know if you want to be added as a maintainer.

**Comment by EugeneLoy** [comment]
@slel 

> [...] having coq-jupyter packaged for Conda
would be nice [...]
> [...] and this is now done [...]

Sounds great! Thank you!

> let me know if you want to be added as a maintainer.

I am not familiar with packaging for Conda yet, however, I guess, it makes sense for me to join you in maintaining this.

Meanwhile, `coq_jupyter` designed to work with `coq`, starting from version `8.6`. I might be mistaken, but it does not look like this is reflected in recipe. Could you, please, check it out?

**Comment by Zimmi48** [comment]
> Meanwhile, `coq_jupyter` is designed to work with `coq`, starting from version `8.6`. I might be mistaken, but it does not look like this is reflected in recipe. Could you, please, check it out?

I don't think that this is a problem because the Conda package for `coq_jupyter` explicitly depends on the Coq package, and the Coq version that is packaged is the latest stable one (8.9.1).

**Comment by EugeneLoy** [comment]
> `coq_jupyter` explicitly depends on the Coq package, and the Coq version that is packaged is the latest stable one (8.9.1).

Makes sense. This makes it no-issue then.

**Pull request merged**
